server:
  host: 0.0.0.0
  port: 8080
db:
  username: root
  password: password
  host: bank.chi60uym6kv7.ap-south-1.rds.amazonaws.com
  port: 5432
  name: bank
  sslmode: disable
token:
  symmetric: Kg4gc&+9v4vLq;kqK#CNtE}hW3dNn:VM
  access_token_duration: 15m
